version: '3.8'

services:
  apache:
    image: httpd:2.4
    ports:
      - "8080:80"
    volumes:
      - ../dev/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
    depends_on:
      - react-app
      - middlewarenode
      - chessserver
      - stockfishserver

  react-app:
    build: ../../react-ystemandchess
    container_name: react-app
    expose:
      - "3000"

  middlewarenode:
    build: ../../middlewareNode
    container_name: middlewarenode
    expose:
      - "8000"
    volumes:
      - ../../middlewareNode/config/default.json:/app/config/default.json:ro

  chessserver:
    build: ../../chessServer
    container_name: chessserver
    expose:
      - "3001"

  stockfishserver:
    build: ../../stockfishServer
    container_name: stockfishserver
    expose:
      - "9324"
