export const themesName = {
    "mate": "Checkmate",
    "mateIn1": "Mate in 1",
    "mateIn2": "Mate in 2",
    "mateIn3": "Mate in 3",
    "middlegame": "Middlegame",
    "endgame": "Endgame",
    "opening": "Opening",
    "advantage": "Advantage",
    "crushing": "Crushing",
    "fork": "Fork",
    "pin": "Pin",
    "skewer": "Skewer",
    "discoveredAttack": "Discovered Attack",
    "deflection": "Deflection",
    "sacrifice": "Sacrifice",
    "promotion": "Promotion",
    "underPromotion": "Under Promotion",
    "castling": "Castling",
    "enPassant": "En Passant",
    "kingsideAttack": "Kingside Attack",
    "queensideAttack": "Queenside Attack",
    "defensiveMove": "Defensive Move",
    "clearance": "Clearance",
    "interference": "Interference",
    "intermezzo": "Intermezzo",
    "zugzwang": "Zugzwang",
    "master": "Master Game",
    "masterVsMaster": "Master vs Master",
    "short": "Short Puzzle",
    "long": "Long Puzzle",
    "veryLong": "Very Long Puzzle",
    "oneMove": "One Move",
    "equality": "Equality",
    "advancedPawn": "Advanced Pawn",
    "pawnEndgame": "Pawn Endgame"
};

export const themesDescription = {
    "mate": "Deliver checkmate to win the game immediately.",
    "mateIn1": "Find the move that delivers checkmate in one move.",
    "mateIn2": "Find the sequence that leads to checkmate in two moves.",
    "mateIn3": "Find the sequence that leads to checkmate in three moves.",
    "middlegame": "A puzzle from the middle phase of the game.",
    "endgame": "A puzzle from the final phase of the game.",
    "opening": "A puzzle from the opening phase of the game.",
    "advantage": "Gain a significant advantage over your opponent.",
    "crushing": "Deliver a crushing blow to your opponent's position.",
    "fork": "Attack two or more pieces simultaneously.",
    "pin": "Restrict an opponent's piece from moving.",
    "skewer": "Force a valuable piece to move and capture a less valuable piece behind it.",
    "discoveredAttack": "Move one piece to reveal an attack from another piece.",
    "deflection": "Force an opponent's piece away from defending something important.",
    "sacrifice": "Give up material to gain a positional or tactical advantage.",
    "promotion": "Promote a pawn to a more powerful piece.",
    "underPromotion": "Promote a pawn to something other than a queen.",
    "castling": "Use the special castling move.",
    "enPassant": "Use the special en passant capture.",
    "kingsideAttack": "Launch an attack on the opponent's kingside.",
    "queensideAttack": "Launch an attack on the opponent's queenside.",
    "defensiveMove": "Make a defensive move to protect your position.",
    "clearance": "Clear a square or line for another piece.",
    "interference": "Block an opponent's piece from defending.",
    "intermezzo": "Play an in-between move before the expected continuation.",
    "zugzwang": "Put your opponent in a position where any move worsens their position.",
    "master": "A puzzle from a master-level game.",
    "masterVsMaster": "A puzzle from a game between masters.",
    "short": "A puzzle that can be solved quickly.",
    "long": "A puzzle that requires several moves to solve.",
    "veryLong": "A puzzle that requires many moves to solve.",
    "oneMove": "A puzzle that can be solved in one move.",
    "equality": "Achieve an equal position.",
    "advancedPawn": "Use an advanced pawn effectively.",
    "pawnEndgame": "A puzzle focusing on pawn endgame technique."
};