apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-ctrl
spec:
  rules:        
  - http:
      paths:
      - path: /chessclient(/|$)(.*)
        backend:
          serviceName: chessclient
          servicePort: 80
